linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true  govet:
    check-shadowing: truelinters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused
    - deadcoderun:
  timeout: 5m
  issues-exit-code: 